### ISSUE TITLE
Production logger: rill-pino-logger 

### ISSUE THREAD

**Issue by davidmarkclements** [rill-js/rill#11]
Hey @DylanPiercey 

rill looks really promising!

I made this http://npm.im/rill-pino-logger - it provides high speed request logging, specifically designed for production servers via http://npm.im/pino

This is the first production logger for rill :bowtie: 

Would you be up for adding it to the [wiki](https://github.com/rill-js/rill/wiki) ?

**Comment by DylanPiercey** [comment]
Added to the wiki, thanks for your work! Looking forward to trying the logger out this weekend.

Just so you know, although Rill is production ready (and has been in prod for about ~6 months on ~15 sites) I have not officially announced it to the world. The reason is that I have been procrastinating on making a documentation website. After that is complete I will be announcing it on social media, reddit, and the like.

Thanks again for checking it out and i'd love to here any questions or issues you have.

**Comment by DylanPiercey** [comment]
@davidmarkclements, thanks again for trying Rill.

I am trying to improve to documentation and lower the barrier to entry to the project and am wondering what issues you ran into, if you still use Rill and what things you think I have failed to mention in the docs about the project?

Answering these questions would be a huge help!
