### ISSUE TITLE
Rill with redux usage example

### ISSUE THREAD

**Issue by stanonyime** [rill-js/rill#15]
Does rill play well with the react-redux wrapper? If so, is there any usage example?

**Comment by DylanPiercey** [comment]
I personally have not used Rill with redux. Originally while making Rill (before redux was released) I used my own version of flux similar to http://fluxible.io/ which worked pretty well.

Ultimately I phased this out because I realized that the way flux architectures tend to work (again no experience with redux) is very similar to the way that RPC/REST api's work. Since Rill basically brings both of these things to the browser I was able to emulate much of the usefulness of a flux architecture using plain old http requests (handled with Rill typically in the browser).

For state I use [@rill/loader](https://github.com/rill-js/loader) and [@rill/session](https://github.com/rill-js/session) and have built 2 apps and ~15 websites so far. It seems to be working pretty good!

Having said that I would love to see people take Rill and test it with other frameworks/libraries. If you would be interested in trying it out (I don't see any real problems coming up in using Rill this way) I would love to hear about your progress. If you would be interested in making an example app using redux that could be very helpful to the community. Otherwise please feel free to keep me up to date in the [gitter](https://gitter.im/rill-js/rill) with your progress!
